{"name": "test_04", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 > 2", "trace": "self = <test221010.public.test.TestOne object at 0x0000017F5E2117C0>\n\n    @allure.story(\"1小于2，用例失败\")\n    def test_04(self):\n        with allure.step(\"先输出描述\"):\n            print(\"第二条用例\")\n>       assert 1>2\nE       assert 1 > 2\n\ntest.py:14: AssertionError"}, "steps": [{"name": "先输出描述", "status": "passed", "start": 1672803177590, "stop": 1672803177590}], "start": 1672803177589, "stop": 1672803177590, "uuid": "f3995bae-dc0d-44ec-a43a-d63967f619e2", "historyId": "cf58dad17b427a94b86c3e3b339beec9", "testCaseId": "7d57e269244a38a2a2b72dc57f26ec7e", "fullName": "test.TestOne#test_04", "labels": [{"name": "story", "value": "1小于2，用例失败"}, {"name": "suite", "value": "test"}, {"name": "subSuite", "value": "TestOne"}, {"name": "host", "value": "DESKTOP-8H78TQB"}, {"name": "thread", "value": "34124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test"}]}